theme: minima
title: An Open Hand
author: Rush Swipas
email: raswipas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my practice page for git. I'm using it to learn git and the usability of github.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
